sudo: false
dist: trusty
language: java
jdk:
  - openjdk8
  - oraclejdk8
before_install:
  - ulimit -c unlimited -S
  - mvn -N io.takari:maven:wrapper
after_success:
  - bash .travis_after_success.sh
cache:
  directories:
    - $HOME/.m2

env:
  global:
    # travis encrypt -r smoketurner/dropwizard-money CI_DEPLOY_USERNAME=
    - secure: "Inmjj+0JDUq6QxkzZTwH4F6Brn+E+sCp8GfudBFpEgWZN+iUyC3vRiNY84Gzy1N2m6XOUWFCvshfXWxb2kQ4jo29KvSKIf0mhHNMZL3++8jxlKC3QLtfRWwgVFMrhTP8S5QX64IJfjW2uA2aqHs/KfrpKx87n9hiXcTgCTUdPX6TBqhKoOmE9kKSrxxRS1iPeCUhYc4LxWhVc8Zh8BN7HmihFnFHouHEHhnZ1FOtb8mAk2X0P6gaPSJ+OdHMa2eEsGTY6OmYXX4cnvwvMlGZeLut+vpVL8D6WUrFeOGeDCsAKzRIeWsyHFxEEs+KogQQnUR0gIa22//1Vd/K2EttPUNknO1UODd1uc6DqxatSeRpvJckS1K3NM7T/Y473GfrQXC7aBRK92yY4jm1pkxEuExJgt1KMqI3RzZwQ2CGa03IoJuRKdKMsRm7/+EAs9U3lLbelZR/okmf+JhsZweaoLb36dKFmf22KGYgjVSHq4nXVeV99j87u+2DPKPE/dBA+rDbeDgZfiZsb6GeF+yL6sUP1HubnnoKKWhBNmBN6yTDqvRNyMMr06eHPNk3dIt4ibJvHU4UcL7D9OqZhOiaRzOfl/ZFJ4zuF56kSGzOUgbJ7KXwK+3Scllg0bRX23ERkB7AryaIyJncQn6uLoxhcVbAgStTSfnXyRI5oYXd1B8="
    # travis encrypt -r smoketurner/dropwizard-money CI_DEPLOY_PASSWORD=
    - secure: "UtFP1oNJ8B5RgY47fe0ddXXKq1KrUT9s3yO73HsXv24Esg7cAubZTiiJLX9HR5nJPtVOANoCq1poy2P1WKEVrDfvLiQBeNvZBqmvH+ExY2oq8hhUMK/tBY8mKvk2Uz4Aog0hCqc/W1sIb0vUFTNBlI7Xmn4bsL8cl//kQAI+hUP011xFtSxWf0gFB0oqST6AE18TlEK2Om5upOJ+JOpLId4MoMGdx1J+edWgBkFtrY5nwpn4e7lPevJyISx87RfksyNlTCDBDwxc+tkD1+rdfVIFGu8SPDMBWsvL6ZL8TBn5FSIGZckROvlrD3qJcA7xwo14uNZOT6Ir0F7o5SuMu9cgoydyRBX2iCC2UCexVBkuLVPPzdPVt8TVWTBmMdyZ42x35INL6+1OETPy0TOthuhBwspEQkbD2xyBirL9Fu3HjvBfudWCx0hE1U+cX/JWiKogtsgWBa43o2oZ7IYHpE6fspT0aUwMDmjDizfNFb/+QxvE/T4tAXln6J03c9oJFcSsCWalyHF7xfnEjeJLCGs9MIOuspnFIeIGGqA8C9JIXK0DTgJTanlffINFiKLdlE2W2aYxzjrSjZLsQhEEYVxvLUHyWObLF5c05uM7N4ThFJOWdrUG8tJUf6g4lLR3K1FxBSFdGjN1QQNxfLD6amIzxHaDd0eAvPxiecHeX8g="
